"use client"

import { useState, useEffect } from "react"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { RefreshCw, Heart } from "lucide-react"

// 365 Daily Affirmations from Dr. Joe Dispenza, Esther Hicks, and similar teachers
const dailyAffirmations = [
  // Dr. Joe Dispenza inspired (Days 1-122)
  "I am greater than my environment, greater than my body, and greater than time.",
  "I choose to live in the elevated emotion of my future, not the familiar emotions of my past.",
  "Every day I am becoming more conscious of my unconscious thoughts and behaviors.",
  "I am breaking the habit of being myself and creating a new version of me.",
  "My thoughts have the power to change my brain and my life.",
  "I am moving from a state of survival to a state of creation.",
  "I choose to think greater than how I feel.",
  "I am rewiring my brain for success and happiness.",
  "I am the creator of my own reality through my thoughts and emotions.",
  "I am becoming supernatural by transcending my limitations.",
  "I choose to live in the present moment where all possibilities exist.",
  "I am transforming my personality to create a new personal reality.",
  "My heart is open and I am living from a place of elevated emotion.",
  "I am breaking free from the chains of my past conditioning.",
  "I choose to be defined by a vision of my future, not a memory of my past.",
  "I am becoming more conscious and aware with each passing day.",
  "I trust in my ability to create the life I desire.",
  "I am aligning my thoughts, feelings, and actions with my highest vision.",
  "I am grateful for the opportunity to evolve and grow.",
  "I choose love over fear in every moment.",
  "I am becoming the person I've always wanted to be.",
  "My meditation practice is transforming my life from the inside out.",
  "I am connected to the infinite field of possibilities.",
  "I choose to respond rather than react to life's challenges.",
  "I am worthy of all the good that life has to offer.",
  "I trust the process of my transformation.",
  "I am creating coherence between my heart and mind.",
  "I choose to live in the frequency of gratitude and joy.",
  "I am becoming more loving, kind, and compassionate.",
  "I trust in the intelligence of my heart.",
  "I am releasing all that no longer serves my highest good.",
  "I choose to see challenges as opportunities for growth.",
  "I am becoming more present and aware in each moment.",
  "I trust in my inner wisdom and guidance.",
  "I am creating a life filled with purpose and meaning.",
  "I choose to focus on what I want, not what I don't want.",
  "I am grateful for my body and treat it with love and respect.",
  "I trust in the perfect timing of my life.",
  "I am becoming more authentic and true to myself.",
  "I choose to live from my heart, not my ego.",
  "I am worthy of love, success, and happiness.",
  "I trust in my ability to heal and transform.",
  "I am creating new neural pathways for success and joy.",
  "I choose to be patient and kind with myself.",
  "I am becoming more conscious of my energy and how I use it.",
  "I trust in the power of my intentions to create my reality.",
  "I am grateful for every experience that has brought me to this moment.",
  "I choose to live in alignment with my values and purpose.",
  "I am becoming more resilient and adaptable.",
  "I trust in my ability to overcome any obstacle.",
  "I am creating a life that reflects my highest values.",
  "I choose to see the beauty and wonder in everyday moments.",
  "I am becoming more generous and giving.",
  "I trust in the abundance of the universe.",
  "I am worthy of receiving all the good that life offers.",
  "I choose to live with an open heart and mind.",
  "I am becoming more creative and innovative.",
  "I trust in my unique gifts and talents.",
  "I am creating positive change in my life and the world.",
  "I choose to be a source of light and love for others.",
  "I am becoming more peaceful and centered.",
  "I trust in the journey of my soul's evolution.",
  "I am grateful for the opportunity to make a difference.",
  "I choose to live with courage and confidence.",
  "I am becoming more wise and discerning.",
  "I trust in my ability to make good decisions.",
  "I am creating harmony and balance in all areas of my life.",
  "I choose to be fully present in each moment.",
  "I am becoming more joyful and playful.",
  "I trust in the power of love to heal and transform.",
  "I am worthy of experiencing miracles in my life.",
  "I choose to live with wonder and curiosity.",
  "I am becoming more connected to my true self.",
  "I trust in the divine plan for my life.",
  "I am grateful for the gift of consciousness.",
  "I choose to live with intention and purpose.",
  "I am becoming more compassionate and understanding.",
  "I trust in my ability to create positive change.",
  "I am worthy of living an extraordinary life.",
  "I choose to embrace change as an opportunity for growth.",
  "I am becoming more aligned with my soul's purpose.",
  "I trust in the wisdom of my heart.",
  "I am grateful for the lessons that challenges bring.",
  "I choose to live with faith and optimism.",
  "I am becoming more loving and accepting of myself.",
  "I trust in my ability to manifest my dreams.",
  "I am worthy of experiencing deep fulfillment.",
  "I choose to live in the energy of possibility.",
  "I am becoming more conscious of my impact on others.",
  "I trust in the interconnectedness of all life.",
  "I am grateful for the opportunity to serve others.",
  "I choose to live with humility and grace.",
  "I am becoming more patient and understanding.",
  "I trust in the perfect unfolding of my life.",
  "I am worthy of experiencing unconditional love.",
  "I choose to live with enthusiasm and passion.",
  "I am becoming more aware of my thoughts and emotions.",
  "I trust in my ability to create lasting change.",
  "I am grateful for the beauty that surrounds me.",
  "I choose to live with integrity and authenticity.",
  "I am becoming more mindful and present.",
  "I trust in the power of my dreams to guide me.",
  "I am worthy of experiencing peace and tranquility.",
  "I choose to live with kindness and compassion.",
  "I am becoming more connected to nature and the earth.",
  "I trust in my ability to heal and be whole.",
  "I am grateful for the gift of this moment.",
  "I choose to live with courage and determination.",
  "I am becoming more aware of my infinite potential.",
  "I trust in the love that flows through me.",
  "I am worthy of experiencing abundance in all forms.",
  "I choose to live with gratitude and appreciation.",
  "I am becoming more aligned with my highest self.",
  "I trust in the journey of my spiritual growth.",
  "I am grateful for the opportunity to evolve.",
  "I choose to live with hope and optimism.",
  "I am becoming more conscious of my choices.",
  "I trust in my ability to create positive outcomes.",
  "I am worthy of experiencing joy and happiness.",
  "I choose to live with love and understanding.",
  "I am becoming more aware of my connection to all life.",
  "I trust in the wisdom of the universe.",
  "I am grateful for the gift of free will.",
  "I choose to live with purpose and meaning.",
  "I am becoming more loving and forgiving.",
  "I trust in my ability to overcome any challenge.",
  "I am worthy of experiencing miracles and magic.",
  "I choose to live with wonder and awe.",
  "I am becoming more present and aware.",
  "I trust in the power of my heart to guide me.",
  "I am grateful for the opportunity to grow and learn.",
  "I choose to live with faith and trust.",

  // Esther Hicks/Abraham inspired (Days 123-244)
  "I am in the process of becoming, and I am enjoying every step of the journey.",
  "I am a powerful creator, and I am creating my reality with every thought.",
  "I choose thoughts that feel good and align me with my desires.",
  "I am worthy of all the good that I desire, and it is flowing to me now.",
  "I trust in the perfect timing of the universe.",
  "I am aligned with the energy of Source, and I feel amazing.",
  "I choose to focus on what I want, and I let the universe handle the how.",
  "I am grateful for the contrast that helps me clarify my desires.",
  "I trust in my inner guidance system and follow my joy.",
  "I am living in the vortex of creation, where all my desires exist.",
  "I choose to feel good now, regardless of current circumstances.",
  "I am attracting all that I desire with ease and joy.",
  "I trust that everything is always working out for me.",
  "I am in harmony with the flow of life.",
  "I choose to see the positive aspects in every situation.",
  "I am grateful for the abundance that surrounds me.",
  "I trust in my ability to create the life I desire.",
  "I am aligned with love, joy, and appreciation.",
  "I choose to live in the moment and enjoy the journey.",
  "I am worthy of receiving all the good that life offers.",
  "I trust in the law of attraction to bring me my desires.",
  "I am feeling good and attracting more reasons to feel good.",
  "I choose to be easy about life and let things flow.",
  "I am grateful for my emotional guidance system.",
  "I trust that I am always in the right place at the right time.",
  "I am aligned with my highest good and greatest joy.",
  "I choose to appreciate what is while eagerly anticipating what is coming.",
  "I am worthy of living an extraordinary life.",
  "I trust in the infinite intelligence of the universe.",
  "I am feeling appreciation for the gift of life.",
  "I choose to be happy regardless of what others are doing.",
  "I am attracting wonderful experiences into my life.",
  "I trust that my desires are being fulfilled in perfect timing.",
  "I am aligned with the energy of pure positive energy.",
  "I choose to look for reasons to feel good.",
  "I am grateful for the freedom to choose my thoughts.",
  "I trust in my ability to manifest my dreams.",
  "I am living in joy and attracting more joy.",
  "I choose to be patient and allow things to unfold naturally.",
  "I am worthy of experiencing unconditional love.",
  "I trust that the universe is conspiring to help me.",
  "I am feeling excited about the possibilities ahead.",
  "I choose to focus on the positive aspects of my life.",
  "I am grateful for the expansion that comes from every experience.",
  "I trust in the perfect orchestration of events in my life.",
  "I am aligned with my inner being and feeling fantastic.",
  "I choose to be kind to myself and others.",
  "I am attracting people and experiences that support my growth.",
  "I trust that I am always guided to my highest good.",
  "I am feeling blessed and highly favored.",
  "I choose to live in the energy of love and appreciation.",
  "I am grateful for the clarity that comes from contrast.",
  "I trust in my ability to choose thoughts that serve me.",
  "I am aligned with the flow of well-being.",
  "I choose to be optimistic about my future.",
  "I am worthy of experiencing miracles in my life.",
  "I trust that everything I need is provided at the perfect time.",
  "I am feeling enthusiastic about life.",
  "I choose to see the beauty in every moment.",
  "I am grateful for the gift of free will.",
  "I trust in the wisdom of my emotions.",
  "I am aligned with my purpose and passion.",
  "I choose to be gentle with myself as I grow.",
  "I am attracting abundance in all areas of my life.",
  "I trust that I am exactly where I need to be.",
  "I am feeling hopeful and optimistic.",
  "I choose to celebrate my progress and growth.",
  "I am grateful for the love that flows through me.",
  "I trust in the power of positive thinking.",
  "I am aligned with the energy of success.",
  "I choose to be present and enjoy this moment.",
  "I am worthy of experiencing deep fulfillment.",
  "I trust that my path is unfolding perfectly.",
  "I am feeling confident and capable.",
  "I choose to focus on solutions rather than problems.",
  "I am grateful for the opportunity to create my reality.",
  "I trust in the infinite possibilities available to me.",
  "I am aligned with the frequency of love.",
  "I choose to be easy-going and relaxed.",
  "I am attracting experiences that bring me joy.",
  "I trust that I am supported by the universe.",
  "I am feeling peaceful and centered.",
  "I choose to appreciate the journey as much as the destination.",
  "I am grateful for the wisdom I gain from every experience.",
  "I trust in my ability to navigate life with grace.",
  "I am aligned with my highest potential.",
  "I choose to be compassionate with myself and others.",
  "I am worthy of experiencing unlimited abundance.",
  "I trust that my desires are important and valid.",
  "I am feeling inspired and motivated.",
  "I choose to look for the gift in every situation.",
  "I am grateful for the contrast that helps me grow.",
  "I trust in the perfect timing of my manifestations.",
  "I am aligned with the energy of pure joy.",
  "I choose to be patient with the process of creation.",
  "I am attracting wonderful surprises into my life.",
  "I trust that I am always being guided and supported.",
  "I am feeling excited about my unlimited potential.",
  "I choose to focus on what brings me joy.",
  "I am grateful for the freedom to create my experience.",
  "I trust in the law of attraction to serve me well.",
  "I am aligned with the flow of prosperity.",
  "I choose to be loving and kind in all my interactions.",
  "I am worthy of experiencing heaven on earth.",
  "I trust that everything is working out for my highest good.",
  "I am feeling blessed beyond measure.",
  "I choose to live in the energy of gratitude.",
  "I am grateful for the gift of imagination.",
  "I trust in my ability to create positive change.",
  "I am aligned with the energy of pure love.",
  "I choose to be happy for no reason other than it feels good.",
  "I am attracting miracles and magic into my life.",
  "I trust that I am worthy of all my desires.",
  "I am feeling amazing and attracting more reasons to feel amazing.",
  "I choose to see the world through the eyes of love.",
  "I am grateful for the opportunity to experience life.",
  "I trust in the infinite wisdom of my inner being.",
  "I am aligned with the energy of pure positive energy.",
  "I choose to be at peace with what is while creating what will be.",
  "I am worthy of experiencing extraordinary love and joy.",
  "I trust that my life is unfolding in perfect divine order.",
  "I am feeling grateful for this moment and all it contains.",
  "I choose to live in the vibration of appreciation.",
  "I am grateful for the endless possibilities before me.",
  "I trust in my ability to choose thoughts that feel good.",
  "I am aligned with the energy of infinite abundance.",
  "I choose to be easy about everything in my life.",
  "I am attracting all that I need to live my dreams.",
  "I trust that I am loved and supported by the universe.",
  "I am feeling wonderful and expecting wonderful things.",

  // Additional Mindfulness & Spiritual Teachers inspired (Days 245-365)
  "I am present in this moment, and this moment is perfect.",
  "I choose to respond to life with wisdom and compassion.",
  "I am connected to the infinite source of love within me.",
  "I trust in the natural flow of life and my place in it.",
  "I am grateful for the opportunity to grow and evolve.",
  "I choose to see the sacred in the ordinary.",
  "I am worthy of peace, love, and happiness.",
  "I trust in my ability to find calm in any storm.",
  "I am connected to all beings through love and compassion.",
  "I choose to live with an open heart and mind.",
  "I am grateful for the lessons that challenges bring.",
  "I trust in the wisdom of my intuition.",
  "I am worthy of experiencing deep inner peace.",
  "I choose to be kind to myself and others.",
  "I am connected to the healing power of nature.",
  "I trust in my ability to transform pain into wisdom.",
  "I am grateful for the gift of consciousness.",
  "I choose to live with mindful awareness.",
  "I am worthy of experiencing unconditional love.",
  "I trust in the interconnectedness of all life.",
  "I am connected to the source of all creativity.",
  "I choose to see beauty in every moment.",
  "I am grateful for the opportunity to serve others.",
  "I trust in my ability to find meaning in all experiences.",
  "I am worthy of experiencing profound joy.",
  "I choose to live with courage and authenticity.",
  "I am connected to the infinite field of possibilities.",
  "I trust in the perfect unfolding of my spiritual journey.",
  "I am grateful for the gift of free will.",
  "I choose to live with humility and grace.",
  "I am worthy of experiencing divine love.",
  "I trust in my ability to heal and be whole.",
  "I am connected to the wisdom of the ages.",
  "I choose to live with faith and hope.",
  "I am grateful for the opportunity to make a difference.",
  "I trust in the power of love to transform everything.",
  "I am worthy of experiencing miracles in my life.",
  "I choose to live with wonder and curiosity.",
  "I am connected to the eternal source of peace.",
  "I trust in my ability to overcome any obstacle.",
  "I am grateful for the gift of this precious life.",
  "I choose to live with intention and purpose.",
  "I am worthy of experiencing boundless happiness.",
  "I trust in the divine plan for my life.",
  "I am connected to the infinite source of wisdom.",
  "I choose to live with compassion and understanding.",
  "I am grateful for the opportunity to love and be loved.",
  "I trust in my ability to create positive change.",
  "I am worthy of experiencing deep fulfillment.",
  "I choose to live with gratitude and appreciation.",
  "I am connected to the source of all healing.",
  "I trust in the journey of my soul's evolution.",
  "I am grateful for the gift of each new day.",
  "I choose to live with joy and enthusiasm.",
  "I am worthy of experiencing unlimited abundance.",
  "I trust in my ability to manifest my highest vision.",
  "I am connected to the eternal flame of love within.",
  "I choose to live with peace and serenity.",
  "I am grateful for the opportunity to grow in wisdom.",
  "I trust in the perfect timing of all things.",
  "I am worthy of experiencing divine grace.",
  "I choose to live with strength and resilience.",
  "I am connected to the source of all inspiration.",
  "I trust in my ability to find light in darkness.",
  "I am grateful for the gift of spiritual awakening.",
  "I choose to live with love and kindness.",
  "I am worthy of experiencing transcendent peace.",
  "I trust in the infinite love that surrounds me.",
  "I am connected to the eternal source of truth.",
  "I choose to live with mindful presence.",
  "I am grateful for the opportunity to serve the highest good.",
  "I trust in my ability to embody divine love.",
  "I am worthy of experiencing cosmic consciousness.",
  "I choose to live with reverence for all life.",
  "I am connected to the source of all blessings.",
  "I trust in the sacred nature of my journey.",
  "I am grateful for the gift of spiritual communion.",
  "I choose to live with devotion and surrender.",
  "I am worthy of experiencing enlightened awareness.",
  "I trust in the divine intelligence that guides me.",
  "I am connected to the eternal source of bliss.",
  "I choose to live with sacred intention.",
  "I am grateful for the opportunity to awaken to truth.",
  "I trust in my ability to embody divine wisdom.",
  "I am worthy of experiencing infinite love.",
  "I choose to live with spiritual dedication.",
  "I am connected to the source of all creation.",
  "I trust in the perfect expression of divine will.",
  "I am grateful for the gift of divine grace.",
  "I choose to live with holy purpose.",
  "I am worthy of experiencing union with the divine.",
  "I trust in the eternal love that I am.",
  "I am connected to the infinite source of all that is.",
  "I choose to live in the light of divine truth.",
  "I am grateful for the opportunity to be love in action.",
  "I trust in the perfect manifestation of divine love.",
  "I am worthy of experiencing the fullness of divine life.",
  "I choose to live as an expression of divine love.",
  "I am connected to the eternal source of divine peace.",
  "I trust in the infinite wisdom of divine love.",
  "I am grateful for the gift of divine presence.",
  "I choose to live in alignment with divine will.",
  "I am worthy of experiencing divine union.",
  "I trust in the eternal truth of divine love.",
  "I am connected to the infinite source of divine joy.",
  "I choose to live as a vessel of divine love.",
  "I am grateful for the opportunity to serve divine love.",
  "I trust in the perfect expression of divine truth.",
  "I am worthy of experiencing divine enlightenment.",
  "I choose to live in the radiance of divine love.",
  "I am connected to the eternal source of divine wisdom.",
  "I trust in the infinite compassion of divine love.",
  "I am grateful for the gift of divine awakening.",
  "I choose to live in the embrace of divine love.",
  "I am worthy of experiencing divine transcendence.",
  "I trust in the eternal presence of divine love.",
  "I am connected to the infinite source of divine light.",
  "I choose to live in the glory of divine love.",
  "I am grateful for the opportunity to embody divine love.",
  "I trust in the perfect realization of divine truth.",
  "I am worthy of experiencing divine liberation.",
  "I choose to live in the freedom of divine love.",
  "I am connected to the eternal source of divine grace.",
  "I trust in the infinite mercy of divine love.",
  "I am grateful for the gift of divine realization.",
  "I choose to live in the bliss of divine love.",
  "I am worthy of experiencing divine perfection.",
  "I trust in the eternal nature of divine love.",
  "I am connected to the infinite source of divine beauty.",
  "I choose to live in the wonder of divine love.",
  "I am grateful for the opportunity to know divine love.",
  "I trust in the perfect fulfillment of divine purpose.",
  "I am worthy of experiencing divine completion.",
  "I choose to live in the wholeness of divine love.",
]

interface DailyAffirmationCardProps {
  category?: string
}

export default function DailyAffirmationCard({ category }: DailyAffirmationCardProps) {
  const [currentAffirmation, setCurrentAffirmation] = useState("")
  const [affirmationIndex, setAffirmationIndex] = useState(0)
  const [isFavorite, setIsFavorite] = useState(false)

  useEffect(() => {
    // Get today's affirmation based on day of year
    const today = new Date()
    const start = new Date(today.getFullYear(), 0, 0)
    const diff = today.getTime() - start.getTime()
    const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
    const todayIndex = (dayOfYear - 1) % dailyAffirmations.length

    setAffirmationIndex(todayIndex)
    setCurrentAffirmation(dailyAffirmations[todayIndex])
  }, [])

  const getRandomAffirmation = () => {
    const randomIndex = Math.floor(Math.random() * dailyAffirmations.length)
    setAffirmationIndex(randomIndex)
    setCurrentAffirmation(dailyAffirmations[randomIndex])
    setIsFavorite(false)
  }

  const toggleFavorite = () => {
    setIsFavorite(!isFavorite)
    // In a real app, this would save to user's favorites
  }

  return (
    <Card className="mindful-card sticky top-6">
      <CardHeader className="text-center pb-4">
        <CardTitle className="flex items-center justify-center text-taupe-800">
          <Heart className="w-5 h-5 mr-2 text-rose-400" />
          Daily Inspiration
        </CardTitle>
        <p className="text-xs text-taupe-600">Day {affirmationIndex + 1} of 365</p>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="bg-gradient-to-r from-amber-50 to-stone-50 p-6 rounded-xl border border-amber-200/50 text-center">
          <p className="text-taupe-800 font-serif text-base leading-relaxed italic">"{currentAffirmation}"</p>
        </div>

        <div className="flex gap-2">
          <Button
            onClick={getRandomAffirmation}
            variant="outline"
            className="flex-1 border-sage-300 text-taupe-700 hover:bg-sage-50"
          >
            <RefreshCw className="w-4 h-4 mr-2" />
            Choose Another
          </Button>

          <Button
            onClick={toggleFavorite}
            variant={isFavorite ? "default" : "outline"}
            className={`${
              isFavorite ? "bg-rose-400 hover:bg-rose-500 text-white" : "border-rose-300 text-rose-600 hover:bg-rose-50"
            }`}
          >
            <Heart className="w-4 h-4" fill={isFavorite ? "currentColor" : "none"} />
          </Button>
        </div>

        <div className="text-center pt-2">
          <p className="text-xs text-taupe-500">Wisdom from spiritual teachers and thought leaders</p>
        </div>
      </CardContent>
    </Card>
  )
}
